### ISSUE TITLE
Not-Crushing Zinc and Copper/Problem with liquids

### ISSUE THREAD

**Issue by Victor892103** [Exzotic5485/Create-Broken-Bad-Fabric#2]
![4](https://github.com/Exzotic5485/Create-Broken-Bad-Fabric/assets/149991088/6e4ca54d-2410-40ec-a20e-9a837b22ecd4)
I installed this mod on 1.20.1 with jei and some other mods. There is no recipe for crushed zinc and copper in jei. I tried to crush copper/zinc, but there is no result. Also it shows 0mb craftable of some liquids in this mod. 
![3](https://github.com/Exzotic5485/Create-Broken-Bad-Fabric/assets/149991088/b620f82d-1a11-43b4-bc4e-d3237807deb1)
![2](https://github.com/Exzotic5485/Create-Broken-Bad-Fabric/assets/149991088/61dd4907-1e7c-4ee3-91a6-3423eba8f697)
![1](https://github.com/Exzotic5485/Create-Broken-Bad-Fabric/assets/149991088/6059e01f-6973-4e82-bef0-9472b8130fe5)

**Comment by Exzotic5485** [comment]
Hey! Sorry for such a late response.
This should be fixed in the most recent update, thanks for reporting it.

Downloads:
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/create-broken-bad-fabric)
[Modrinth](https://modrinth.com/mod/create-broken-bad-fabric)
[Github](https://github.com/Exzotic5485/Create-Broken-Bad-Fabric/releases)
